### ISSUE TITLE
Remove the use of moduleRegisterApi

### ISSUE THREAD

**Issue by MeirShpilraien** [RedisAI/RedisAI#113]
Instead use the register api which was introduce in redis 5.0.4.
If the api does not exist continue without it.

**Comment by lantiga** [comment]
Hi @MeirShpilraien, can you point me to an example for the right way to use the register API in other Redis modules? Thanks!

**Comment by MeirShpilraien** [comment]
Actually I do not have such example yet, But I am planning to change gears and redisearch soon, I will sent you the PR's to take a look.

**Comment by lantiga** [comment]
Great, thanks Meir

**Comment by MeirShpilraien** [comment]
@lantiga Pls take a look at this PR: https://github.com/RedisLabsModules/RedisGears/pull/119/files
Especially the parts that use `RedisModule_ExportSharedAPI` and `RedisModule_GetSharedAPI` , those need to be used instead of `moduleRegisterApi`.
