### ISSUE TITLE
Cache protobuf instead of re-serializing on every RDB and AOF

### ISSUE THREAD

**Issue by lantiga** [RedisAI/RedisAI#122]

**Comment by gkorland** [comment]
@lantiga  won't it waste too much memory?

**Comment by lantiga** [comment]
My concern is mainly around a model on the GPU: it doesn't make sense to me to periodically serialize it (i.e. fetch it from GPU) if it doesn't change.
To save memory we could use a tmp file and re-serialize only if it's not there, making sure the former doesn't go out of date. What do you think?

**Comment by lantiga** [comment]
Maybe give the option to use cache or re-serialize

**Comment by lantiga** [comment]
I suspect this is related to #302. Serialization could be triggered while the model is running in another thread. We need to switch to caching to be safe and avoid locks.
Will send a PR shortly.
