### ISSUE TITLE
Jupyter notebook example to ONNXRuntime

### ISSUE THREAD

**Issue by lantiga** [RedisAI/RedisAI#124]
http://onnx.ai/sklearn-onnx/auto_examples/plot_convert_model.html#sphx-glr-auto-examples-plot-convert-model-py [Small]

**Comment by hhsecond** [comment]
@lantiga I assume this refers to the jupyter example for training, exporting and loading the model onto RedisAI rather than ONNXRuntime? If yes, this could be useful?
https://colab.research.google.com/drive/1OefFEa073bnggrO2AUbu83Fcof_hGA4K

**Comment by lantiga** [comment]
Looks good! Can you make it a Jupyter Notebook and submit a PR? Thanks!

**Comment by hhsecond** [comment]
@lantiga Done. It depends on the redisai-py ONNX PR. But for now, we are installing the package from specific github branch.
