### ISSUE TITLE
Segfault on RDBSave if buffer is freed

### ISSUE THREAD

**Issue by hhsecond** [RedisAI/RedisAI#125]
`RAI_Model_RdbSave` causes segfault while freeing buffer. This is commented in master for time being.

**Comment by lantiga** [comment]
For the records, this is due to memory being allocated using `malloc` on the `libtorch_c` side, but then freed with `RedisModule_Free` on the RedisAI side, when Redis is built with `jemalloc`.

**Comment by lantiga** [comment]
Ok, tests are green again. Merged and closing
