### ISSUE TITLE
RedisAI doesn't throw error/warning if user tries to set GPU when GPU is not available

### ISSUE THREAD

**Issue by hhsecond** [RedisAI/RedisAI#155]
Other than PyTorch, none of the backends throws an error or a warning if the user tries to set the model with GPU when GPU is not available. There are #TODOs in the source to fix this already. Keeping the issue open to track it for the GA perhaps, because it could cause serious skepticism in certain situations.

**Comment by hhsecond** [comment]
ONNXRuntime still needs to do this check dynamically but since the dynamic allocation of CUDA is decided to do in the future, this chek can also be implemented then

**Comment by lantiga** [comment]
I think since we can load backends dynamically and we can build ONNXRuntime with multiple backends (CPU, GPU, TensorRT, OpenVINO, etc), we can eventually leave the dynamicity for when the user chooses what backend to load, rather than within ONNXRuntime.

**Comment by lantiga** [comment]
We can have several ONNXRuntime backends, one per executor. This way they'll also be smaller and with fewer dependencies.

**Comment by hhsecond** [comment]
Make sense. In that case, I should leave this issue opened since the CUDA check won't happen for ORT if the default installation is CPU

**Comment by lantiga** [comment]
Are you saying that if ORT is built for CPU and you request GPU we won't return an error, right?

**Comment by hhsecond** [comment]
No, if ORT is built with CPU, then we will return an error if user request for a GPU execution.

But if RedisAI is built without DEVICE var (or DEVICE=cpu) it throws an error if user request GPU even if the loaded ORT backend is running on GPU. We have problem for the other case as well -  RedisAI is built for GPU and loaded ORT backend is CPU only

 https://github.com/RedisAI/RedisAI/blob/19d15c42779423cccd7830aefc971761f9dd7e7f/src/backends/onnxruntime.c#L269-L279

**Comment by lantiga** [comment]
Say we have two ORT backends, like `redisai_onnxruntime_cpu.so` and `redisai_onnxruntime_gpu.so`
- the moment we load `redisai_onnxruntime_gpu.so` it will throw an error if there's no GPU or CUDA on the machine
- if we load `redisai_onnxruntime_cpu.so` and request GPU, it returns an error (which is correct)

In other words, it doesn't really matter how you build `redisai.so`, only the backends counts. Does this make sense or I'm being overly dense? :-)

**Comment by hhsecond** [comment]
Thanks for the clarification. Closing the issue
