### ISSUE TITLE
AI.MODELRUN and AI.SCRIPTRUN are not declaring keys properly

### ISSUE THREAD

**Issue by MeirShpilraien** [RedisAI/RedisAI#160]
The only declared key is the model/script (and not the tensors). Also there is not early exit in the code to not actually execute the command:
```
  if (RedisModule_IsKeysPositionRequest(ctx)) {
    RedisModule_KeyAtPos(ctx, 1);
  }
```

**Comment by lantiga** [comment]
Addressed by #161, closing
