### ISSUE TITLE
Why it always report "ERR: GPU requested but CUDA not available"

### ISSUE THREAD

**Issue by haiyang-tju** [RedisAI/RedisAI#164]
I have a GPU, my code runs ok, and it print "Info: cuda is available, run on gpu":
```
#include "torch/script.h"
#include "torch/torch.h"
#include <iostream>

int main(int argc, const char* argv[])
{
    if(torch::cuda::is_available())
    {
        std::cout << "Info: cuda is available, run on gpu" << std::endl;
    }
    return 0;
}
```

I build RedisAI normally, with "DEPS_DIRECTORY=deps bash ./get_deps.sh".

But when I use the redisai-examples from backend pytorch, code like that:
```
import redisai as rai
import mlut
con = rai.Client(host='localhost', port=6379, db=0)

pt_model_path = '../models/pytorch/imagenet/resnet50.pt'
script_path = '../models/pytorch/imagenet/data_processing_script.txt'

pt_model = mlut.load_model(pt_model_path)
script = mlut.load_script(script_path)

out1 = con.modelset('imagenet_model', rai.Backend.torch, rai.Device.gpu, pt_model)
```
the last line will throw the exception `redis.exceptions.ResponseError: GPU requested but CUDA not available`, and the redis print an error message.

```
1:M 23 Jul 2019 07:57:51.348 * Module 'ai' loaded from /usr/lib/redis/modules/redisai.so
1:M 23 Jul 2019 07:57:51.348 * Ready to accept connections
ERR: GPU requested but CUDA not available
ERR: GPU requested but CUDA not available
```

I searched the src code, and find the message code. It is an if conditional statement：
```
    if (aten_device == at::DeviceType::CUDA && !torch::cuda::is_available()) {
      throw std::logic_error("GPU requested but CUDA not available");
    }
    module->to(aten_device);
```

My code snippet above is normal, and print the gpu info. Why this code is not? I basically did it according to the `Dockerfile`, did I miss something?

@lantiga Can you help me? Thanks very much!

**Comment by lantiga** [comment]
Hi @haiyang-tju, thanks for your patience.

A few questions to start:
- do other backends (like TF) work on the GPU?
- what CUDA version do you have on your system? It may be a CUDA version mismatch related to the binaries.

One way to find out may be if you link your libtorch C++ code to the same libtorch as contained in the `deps` directory, and make sure that you link to them (and not to other version) when you run.

**Comment by haiyang-tju** [comment]
I removed the other backends and only left libtorch. Some configurations are as follows:
- OS: jetson nano l4t, jetpack 4.2.1
- CUDA version is 10.0, and with cudnn7.3.1
- Docker version 18.09.2, build 6247962
- libtorch-1.2.0a0 compiled with the same version of cuda and cudnn

I modified the `get_deps.sh` and all lib files are compiled by my own by docker.  I successfully compiled the entire module, and it runs ok. 

But when I running the samples, it shows unable to get GPU access in this container. Particularly weird, I can get the access when I run my own code snippet. The `libtorch` I used in my own code snippet is also in the `deps` directory.

My description may be somewhat unclear. Thanks for your kindly reply.

**Comment by lantiga** [comment]
Se you're going on the Jetson. That's cool!

Is it possible for you to try out CUDA 9.0? This is what we test on.

**Comment by haiyang-tju** [comment]
It may be a limitation of Docker on jetson. I repeated it on the host and the GPU access are normal.

What I am puzzled about now is that the same code snippet execution of two programs in the same container has different results.

I made corresponding changes to the source code of RedisAI. And at this moment, everything goes ok.

A small suggestion, it is best to make a configuration switch for different backends in case the user only needs one backend. 

THANKS @lantiga

**Comment by lantiga** [comment]
Great, thanks for the feedback.
We have a PR about to be merged in which backends will be loadable dynamically. So you can specify them from the command line or through a CONFIG LOADBACKEND command, passing the backend type and the location of the backend library (eg redisai_onnxruntime.so).
You can of course load one or more than one, in any CPU/GPU combination.

**Comment by lantiga** [comment]
@haiyang-tju Before we close this, would you be willing to share your experience with the Jetson? We are working at an `arm64` branch, so this getting information on how you got this working, roadblocks etc, would be quite useful for us. Thanks!

**Comment by haiyang-tju** [comment]
OK. There are not too many special steps. According to the steps in the [Dockerfile](https://github.com/RedisAI/RedisAI/blob/master/Dockerfile), and switched the corresponding ARM files.

The steps are roughly as follows:
- 1 Configure your jetson system. It is recommended to use sdkmanager to install the jetson system, so that you can choose to install the corresponding components.
- 2 Built your aarch64 version redis. You can use the steps in this [Dockerfile](https://github.com/docker-library/redis/blob/ede954da6de61f1d6a8572db4cd7bdf1278a2815/5.0/Dockerfile) of `[arm64v8/redis](https://hub.docker.com/r/arm64v8/redis)`
- Or you can simply use the [source code](http://download.redis.io/releases/redis-5.0.5.tar.gz) of redis to compile and build. [Just `make && sudo make install`]
- Confirm the installation of redis.
- 3 Built `RedisAI` as [it](https://github.com/RedisAI/RedisAI/blob/master/Dockerfile#L23) and [it](https://github.com/RedisAI/RedisAI/blob/master/Dockerfile#L30) described.

Enjoy it.

The roadblocks may be on virtualization of Docker with GPU. The above steps can be built in Docker base on [nvidia:l4t-base](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base), but there will be an error at runtime. 

**Known limitation: The base l4t image doesn’t allow you to statically compile with all CUDA libraries. Only libcudadevrt.a and libcudart_static.a are included.** quoted from [here](https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson#building-cuda-in-containers-on-jetson).

Maybe you can clean it up, and let me knows, thanks.

In addition, the master version of libtorch is undergoing great changes by merging caffe2, not recommended for direct use.

**Comment by K-Jo** [comment]
@rafie
