### ISSUE TITLE
crash on AI.CONFIG  LOADBACKEND TORCH

### ISSUE THREAD

**Issue by pythoner** [RedisAI/RedisAI#171]
the issue is described  [here](https://github.com/RedisGears/EdgeRealtimeVideoAnalytics/issues/8)

**Comment by lantiga** [comment]
Thanks for the report @pythoner

**Comment by lantiga** [comment]
From pytorch/pytorch#21627, installing `gcc4.9.2` should fix the issue.

**Comment by pythoner** [comment]
Load torch backend successfully using gcc 4.9.2
