### ISSUE TITLE
Bump all backends to CUDA 10

### ISSUE THREAD

**Issue by lantiga** [RedisAI/RedisAI#181]
After merging #179, we will be able to move all backends to CUDA 10.

Specifically we will:
- bump libtensorflow to 1.14 (https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.14.0.tar.gz)
- bump libtorch to 1.2 (https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-latest.zip)

**Comment by hhsecond** [comment]
Just FYI: TF will have 1.15 out by this week

**Comment by lantiga** [comment]
Doh! :-) Thank you @hhsecond, I hope it won't depend on CUDA 10.1 or we're back to square 1...

I would go ahead with this PR for now, and evaluate 1.15 in a week. The switch from 1.12 to 1.14 was very smooth for us, hopefully it will be the same. The only show stopper (at least for the moment) would be a requirement for CUDA 10.1.

**Comment by hhsecond** [comment]
Let's merge this for sure. IMO 1.15 will not be a major upgrade and will be with the current cuda. Also, the release could get delayed for another week or so.
