### ISSUE TITLE
Tensorflow Module not loaded

### ISSUE THREAD

**Issue by Akhtar303** [RedisAI/RedisAI#198]
Thanks for your RedisAI implementation 
I am facing this issue 
Module  /home/akhtar/Desktop/streaming/EdgeRealtimeVideoAnalytics/RedisAI/build/redisai_tensorflow.so does not export RedisModule_OnLoad() symbol. Module not loaded.

same issue for redisai_tensorflow and redisai_torch

Thanks

**Comment by lantiga** [comment]
Hi @Akhtar303, you shouldn't load `redisai_tensorflow.so` as a Redis module, these are instead RedisAI backends (they expose a different ABI).

Just load `redisai.so` as a module, RedisAI will load the backend on demand as appropriate when you call `MODELSET`.
You can also pre-load a backend using, e.g. `AI.CONFIG LOADBACKEND TF redisai_tensorflow/redisai_tensorflow.so`, or at the command-line

```bash
redis-server --loadmodule install-cpu/redisai.so TF redisai_tensorflow/redisai_tensorflow.so TORCH redisai_torch/redisai_torch.so
```

**Comment by Akhtar303** [comment]
Thanks @lantiga for your Immediate reply.
when I Just load redisai.so as a module RedisAI will not load the backend,  when  I call MODELSET   
i.e  
res = conn.execute_command('AI.MODELSET', 'yolo:model', 'TF', args.device, 'INPUTS', 'input', 'OUTPUTS', 'output', model)

Error
redis.exceptions.ResponseError: ERR: could not load backend
 I am working on RedisGears/EdgeRealtimeVideoAnalytics this repo
Link - https://github.com/RedisGears/EdgeRealtimeVideoAnalytics
when I load with commond line which you suggest 
i.e
redis-server --loadmodule install-cpu/redisai.so TF redisai_tensorflow/redisai_tensorflow.so TORCH redisai_torch/redisai_torch.s

it genrate this error

6577:M 03 Sep 2019 23:27:53.885 # Module install-cpu/redisai.so failed to load: install-cpu/redisai.so: cannot open shared object file: No such file or directory
6577:M 03 Sep 2019 23:27:53.885 # Can't load module from install-cpu/redisai.so: server aborting

Thanks

**Comment by lantiga** [comment]
Hi @Akhtar303,
can you describe how you built RedisAI. It is very important to run the `make install` step after `make`. This will generate an `install-cpu` or `install-gpu` directory inside the RedisAI directory, which contains redisai.so and the backends, with the correct dependencies in place.

You should `loadmodule` the `redisai.so` inside the install directory. If this solves things for you, I’ll make sure this point is properly stressed in the README.

Let me know, thanks for your feedback

**Comment by Akhtar303** [comment]
Thanks for your reply I am following these for build

bash get_deps.sh cpu

Once the dependencies are downloaded, build the module itself. Note that
CMake 3.0 or higher is required.

mkdir buildcd build
cmake ..
make && make installcd ..

**Comment by lantiga** [comment]
Can you check that there’s an `install-cpu` directory in the RedisAI directory?
If so, you can start `redis-server` using the `redisai.so` module inside `install-cpu`. If you do that, the default backend should load automatically.

**Comment by Akhtar303** [comment]
Thanks alot @lantiga  Issue has resolved with install-cpu.
