### ISSUE TITLE
RedisAI needs to manage the number of background threads for backends

### ISSUE THREAD

**Issue by hhsecond** [RedisAI/RedisAI#203]
Libtorch uses all the available cors (including hyperthreaded ones) which causes performance degradation.

**Comment by K-Jo** [comment]
@hhsecond, can we make an abstraction layer in general between the backends and redisai to specify which resources can be used by the redis process?

**Comment by hhsecond** [comment]
We could. Currently, the only libtorch has this problem though

**Comment by filipecosta90** [comment]
@lantiga @K-Jo @hhsecond and @gkorland I believe this is of most importance, specifically for solutions with multiple shards on the same machine. 
I would stick to the same nomenclature of TF and Pytorch and add two loadtime configurations:
- INTRA_OP_PARALLELISM ( multiple threads within the ops )
- INTER_OP_PARALLELISM ( explicitly use a global (per process) thread pool )
If set to 0 or not set the system will not force and use the default per backend configs. 
At least [PyTorch](https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html#runtime-api) and [TF](https://github.com/tensorflow/tensorflow/issues/13853#issuecomment-466408718)

**Comment by filipecosta90** [comment]
#322 adds the possibility to specify both configurations(INTRA_OP_PARALLELISM and INTER_OP_PARALLELISM). Only enforced for now on Tensorflow backend.

**Comment by filipecosta90** [comment]
@hhsecond @gkorland @lantiga and @K-Jo I've done a quick test with the added configurations of interop and intra-op parallelism of #322, and even on a local dev environment this plays a big role in the achievable ops/sec and overall inference latency. 
For OSS RedisAI with financialnet aibench we see that keeping the background threads limited is beneficial. This is directly bound to the model complexity ( which enforces the need to be able to set/controll the degree of parallelism on the backends ). 

INTER_OP_PARALLELISM | INTRA_OP_PARALLELISM | infnerences/sec | RTT q50 latency (ms)
-- | -- | -- | --
1 | 1 | 16867 | 0.46
2 | 1 | 11666 | 0.65
2 | 2 | 11657 | 0.66
4 | 2 | 10506 | 0.72

**Comment by hhsecond** [comment]
Ideally, doing this for PyTorch is straight-forward with these two functions

```
torch::set_num_threads
torch::set_num_interop_threads
```
But there seems to be an internal bug in PyTorch that leads libtorch to not read values set by the above functions. This will work absolutely fine in the python world. Also, it apparently [got fixed in 1.6](https://github.com/pytorch/pytorch/issues/19213). So we might need to wait till 1.6/1.7 integration? @lantiga 

Note: A detailed discussion about unifying the `num_thread` operations is [here](https://github.com/pytorch/pytorch/issues/19001)

**Comment by lantiga** [comment]
Hey @hhsecond, since RedisAI 1.2.0 will sport 1.6, I would make the changes right away and start with testing against 1.6 manually until we merge the backend upgrade
