### ISSUE TITLE
Dependency fetching script is broken

### ISSUE THREAD

**Issue by hhsecond** [RedisAI/RedisAI#204]
`bash get_deps.sh gpu` triggers an error while fetching libtorch. I am assuming this URL is wrong 
`https://s3.amazonaws.com/redismodules/pytorch/libtorch-cu100-linux-x86_64-1.2.0.tar.gz
`
Also `bash get_deps.sh` is not taking `gpu` as the default argument. Is that intentional?

**Comment by lantiga** [comment]
cc @rafie
