### ISSUE TITLE
Optimized TF compilation to use GPU/CUDA

### ISSUE THREAD

**Issue by gkorland** [RedisAI/RedisAI#22]

**Comment by lantiga** [comment]
On Linux RedisDL now builds against the GPU version by default.
To force it to build against the CPU version, just do
```
bash get_deps.sh cpu
```
This means that everything will run on GPU if CUDA finds a device. If not, it will fall back to CPU.
To disable GPU even if one is found, run `redis` with the `CUDA_VISIBLE_DEVICES` environment variable set to empty.

Next thing in line is specifying the device at the Redis command level.

**Comment by lantiga** [comment]
> Next thing in line is specifying the device at the Redis command level.
So, following internal discussion we'll not be pursuing device selection at the command-level, but rather globally, using an upcoming `dl.config` command.

**Comment by lantiga** [comment]
Closing as outdated.
