### ISSUE TITLE
ORT does not like deviceid=-1 for CUDA backend

### ISSUE THREAD

**Issue by hhsecond** [RedisAI/RedisAI#228]
`OrtSessionOptionsAppendExecutionProvider_CUDA` throws **invalid device ordinal** error if `deviceid` is equal to -1. Since our `parseDeviceStr` always set `deviceid=-1` if device ID is not explicitly specified by the user, ORT GPU execution always breaks with this error

**Comment by lantiga** [comment]
Hi @hhsecond, absolutely, I was convinced this was already the case.

**Comment by lantiga** [comment]
Merged #229
