### ISSUE TITLE
Time complexity of each API command

### ISSUE THREAD

**Issue by filipecosta90** [RedisAI/RedisAI#257]
going through the documentation I find some commands with time complexity info and others without.
Example of one with time complexity info:
https://oss.redislabs.com/redistimeseries/commands/#complexity_2

Example of one without time complexity info:
https://oss.redislabs.com/redistimeseries/commands/#tsget

**Comment by lantiga** [comment]
To address in #319

**Comment by itamarhaber** [comment]
I'm not sure there's any point in doing asymptotical complexity analysis for anything in RedisAI... Setting and getting Tensors, mebbe, eh but the real beef is in models, scripts and DAGs where we really have no insights.

Recommending to close this.
