### ISSUE TITLE
TF doesn't support old GPU devices with CC < 6.0

### ISSUE THREAD

**Issue by hhsecond** [RedisAI/RedisAI#260]
This to keep a track of an issue @rafie raised while testing GPU test cases on EC2 g3s.xlarge machines with tesla M60 GPUs which has CC 5.2. TF backend of RedisAI raised below given issue
```
2019-12-29 14:04:34.831620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] 
	Found device 0 with properties:
		name: Tesla M60 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
		pciBusID: 0000:00:1e.0 
2019-12-29 14:04:34.842879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1717] 
	Ignoring visible gpu device (device: 0, name: Tesla M60, pci bus id: 0000:00:1e.0, compute capability: 5.2) with Cuda compute capability 5.2. 
	The minimum required Cuda capability is 6.0.
```

It looks like the an issue with TF core which is fixed in 1.13 - https://github.com/tensorflow/tensorflow/issues/25329

**Comment by lantiga** [comment]
> It looks like the an issue with TF core which is fixed in 1.13 - tensorflow/tensorflow#25329

We are going TF 1.14 though. Shouldn't this be fixed already?

**Comment by hhsecond** [comment]
Alright, then it needs more digging-in. I'll take a look

**Comment by hhsecond** [comment]
@rafie Can you point out the steps to reproduce this issue here please?

**Comment by longbill** [comment]
I am using tfjs-node-gpu, which uses the binary C-API release (https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.14.0.tar.gz)。 My GPU is Titan X, which has cuda capacity 5.2.

I got exactly the same error:

`I tensorflow/core/common_runtime/gpu/gpu_device.cc:1717] Ignoring visible gpu device (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0, compute capability: 5.2) with Cuda compute capability 5.2. The minimum required Cuda capability is 6.0.`

**Comment by lantiga** [comment]
@longbill that's for the report. We are currently doing a memory sanitization pass right now.
As soon as that is done we will upgrade TF to 1.14 and PyTorch to 1.4.0. ETA next week.

**Comment by longbill** [comment]
@lantiga  Thank you, but I've changed my graphic card from TITAN X to GTX 1070 which has 6.1 Cuda capability :) and my problem is solved.
