### ISSUE TITLE
Crash on $REDIS_CLI -x AI.SET GRAPH yolo TF GPU < tiny-yolo-voc.pb

### ISSUE THREAD

**Issue by echiu3** [RedisAI/RedisAI#27]
Running `load_yolo.sh` on MacOS Mojave with Tensorflow 1.12 but encounter "ERR failed creating the graph."

```
./load_yolo.sh 
SET GRAPH
(error) ERR failed creating the graph
SET TENSOR
(error) ERR data length does not match tensor shape and type
GET TENSOR
(error) WRONGTYPE Operation against a key holding the wrong kind of value
RUN GRAPH
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
(error) WRONGTYPE Operation against a key holding the wrong kind of value
GET OUTPUT TENSOR
(error) WRONGTYPE Operation against a key holding the wrong kind of value
```

There does not seem to be a tf-minimal.py equivalent for tiny-yolo-voc.pb.

Also having trouble finding stack trace or logs from redis-cli.

**Comment by lantiga** [comment]
Hi @echiu3, thanks for the report.
Did you install `git lfs` (https://git-lfs.github.com)?
The repo contains some large files that are stored using LFS in order to keep the repo lean. The data files in the repo are only pointers to the actual files, and they are pulled only if you have `git lfs` installed. If not, this would explain `SET GRAPH` failing.

Can you let me know what
`cat tiny-yolo-voc.pb`
returns?

Thanks!

**Comment by echiu3** [comment]
Hi,

I installed `git lfs` and recloned the repo. Everything seems to work now!

`cat tiny-yolo-voc.pb` just printed out a bunch of characters.

Thanks!

**Comment by lantiga** [comment]
Great, thanks for letting us know! Closing the issue.
