### ISSUE TITLE
Add metric infrastructure

### ISSUE THREAD

**Issue by lantiga** [RedisAI/RedisAI#278]
We are looking for a way to extract metrics from a running model, with the aim of:
- selecting the samples that are most interesting, in an [active learning](https://en.wikipedia.org/wiki/Active_learning_(machine_learning)) setting
- detect if a model is degrading with the current inputs compared to some previous operation period

There are a few ways to produce metrics about a running model:
- post-process outputs (in the absence of ground truth)
- run a model multiple times under perturbation and collect outputs, such as approximate Bayesian inference approaches:
  - [Monte Carlo Dropout](https://baal.readthedocs.io/en/latest/notebooks/posteriors.html#Monte-Carlo-Dropout)
  - [Drop Connect](https://baal.readthedocs.io/en/latest/notebooks/posteriors.html#Drop-Connect)

Some of the most popular active learning heuristics (aka _acquisition functions_) to collect interesting samples for the next active learning iteration:
- confidence-based (for classifiers, one shot):
  - largest entropy (pick samples with highest entropy)
  - least confidence (pick samples with lowest confidence of most likely label)
  - largest margin (pick samples with smallest difference between the first and second most likely labels)
- uncertainty-based (requires approximate Bayesian inference machinery):
  - largest variance (pick samples with largest variance from approximate Bayesian inference)
  - largest mean standard deviation (referenced [here](https://arxiv.org/abs/1703.02910))
  - [BALD (original)](https://arxiv.org/abs/1112.5745) (how well the model’s predictions inform us about the model parameters through mutual information)
  - [BALD for image data](https://arxiv.org/abs/1703.02910)
  - [BatchBALD](https://oatml.cs.ox.ac.uk/blog/2019/06/24/batchbald.html) for ranking data in batches, rather than one at a time as in BALD

Ideally, monitoring should allow us to obtain the metrics above as transparently as possible. The user should set a model, configure it, obtain running predictions and running metrics.

In practice, we need to enable users to achieve this result in a way that doesn't assume too much on the structure of the model. We need to provide the building blocks for enabling metrics, rather than providing ones pre-canned. We can start experimenting on the PyTorch backend, and extend to other backends at a future stage.

We can get confidence-based (non-Bayesian) by using SCRIPT (or a related dedicated command. We can take outputs of a model and produce metrics.

Metrics can go into an output key as a tensor, or (better) into a STREAM. The STREAM could also optionally contain the input tensors or somehow reference them.

For Bayesian approximations:
- we need a command to run MODELRUN multiple times, collecting the output and computing metrics (using SCRIPT)
- each run should be perturbed. Perturbations can be obtained, e.g. using Drop Connect by:
  1. zeroing model weights at random (with Bernoulli-drawn mask) at each inference step (Drop Connect); this is quite feasible using PyTorch by multiplying weights in-place using a Bernoulli mask prior to each inference, taking care of backing up the original weights; this is doable on-device;
  2. zeroing activations (MC Dropout); this is more complicated with a generic model (unless we resort to zero entire rows using the Drop Connect strategy above), it would amount to inserting a Dropout layer in the graph, or intercepting and overwriting the intermediate outputs using a hook (although right now e.g. there is no hook for ScriptedModule's in PyTorch, but it may come in the future https://github.com/pytorch/pytorch/issues/34329; an additional issue is that hooks are not supported in the C++ API)
  3. editing graphs to multiply outputs of matrix multiples and convolutions by binary masks, generated at each pass using a Bernoulli distribution; these become additional inputs to the model; they don't need to be exposed as real inputs, they can be generated directly on-device at each inference

**Comment by lantiga** [comment]
# Monitoring facility design

## Requirements

Based on the above, the minimal requirements for a monitoring infrastructure are:
- the ability to collect some of the outputs of a model/script into a persistent collection (similar to a Redis list), rather than an individual tensor
- the ability to submit multiple runs on the same model instead of one (with the caveat that dropout will act the same way on all samples in the batch in the same run, so these runs can't be batched)
- the ability to consume the collection and obtain a single result out of it (using a model/script)

As an advanced requirement for a monitoring infrastructure:
- the ability to modify (perturb) the compute graph to generate metrics, although this is not essential (a model can be exported with perturbation ops built-in)

Supporting running the model multiple times to collect metrics makes a compelling use case for RedisAI: all tensors used to collect a metric don't need to be returned to the caller. They are stored in Redis and can be reduced to a number and deleted by a different client.

## Solution

### New TENSORLIST data type

Given the fact that tensors are considerable in size, we can provide a cap to the size of the list

#### TENSORLIST key [MAXSIZE 100]
initializes an empty list at key.
The list will POP as new elements are PUSHed as soon as MAXSIZE is reached.

### New commands

These are not essential for monitoring but they provide minimal functionality to interact with a TENSORLIST from a client

#### AI.TENSORPOP key [META | BLOB | VALUES]
perform an LPOP on a TENSORLIST

#### AI.TENSORPUSH key data_type shape1 shape2 ... [BLOB data | VALUES val1 val2 ...]
perform an RPUSH on TENSORLIST

### New arguments for MODELRUN and SCRIPTRUN

A set of new arguments are added to MODELRUN and SCRIPTRUN. They also apply to commands inside a DAGRUN.
Except REPEAT, the new arguments qualify inputs and outputs.

#### REPEAT N
repeat the run N times, e.g.
```
MODELRUN m REPEAT 100 INPUTS a b OUTPUTS c d
```
In this case, `a`, `b`, `c` and `d` are TENSORs. Therefore, at each run, inputs are reused, outputs are overwritten (not very useful). REPEAT runs from the same command are never batched.

#### MODELRUN/SCRIPTRUN with a TENSORLIST output
If the command has a TENSORLIST as an output, push to the list instead of performing TENSORSET
```
MODELRUN m REPEAT 100 INPUTS a b OUTPUTS c_list d
```
In this case, each run is performed with the same inputs and overwrites `d`, but it appends tensors to `c_list`.

This construct allows to accumulate the results of multiple runs of a model, as in the case of MC Dropout or Drop Connect, for downstream consumption, for instance by a SCRIPT that computes the standard deviation across results of a run.

The intention here is that `c_list` is not reinitialized at each run, only when `TENSORLIST c_list` is called. This allows to accumulate using multiple calls to MODELRUN:
```
MODELRUN m INPUTS a b OUTPUTS c_list d
MODELRUN m INPUTS a b OUTPUTS c_list d
```
This allows to accumulate results from multiple models (enabling *ensemble* support) or same models across devices.
If convenient, we could add an extra argument `RESET key` where key is an output TENSORLIST, which will reset the list before appending.

#### FOREACH key 
If an input key is holding a TENSORLIST, MODELRUN is ran multiple times, for each of the elements of the list
```
MODELRUN m FOREACH a_list INPUTS a_list b OUTPUTS c_list d
```
In this case, both `a_list` and `c` are TENSORLISTs. As many elements as `a_list` are pushed to `c_list` as a result of `MODELRUN`.

#### CONSUME key
If CONSUME key is specified, and key is an input, elements of the input key are popped as they are processed.
```
MODELRUN m FOREACH a_list CONSUME a_list INPUTS a_list b OUTPUTS c_list d
```
In this case, both `a_list` and `c` are TENSORLISTs. As many elements as `a_list` are pushed to `c_list` as a result of `MODELRUN`.

This case and the previous one could benefit from the RESET argument
```
MODELRUN m FOREACH a_list RESET c_list INPUTS a_list b OUTPUTS c_list d
```
This will run for each element of `a_list` and append outputs to `c_list`, after resetting it to an empty state.

#### Reducing a list
In both the ensemble and MCDropout scenarios, the results of multiple runs are kept in memory and they need to be aggregated using either a MODELRUN or a SCRIPTRUN, before they are accessed. After being processed, the list itself is not interesting and can be reset / deleted (or just vanish in the context of a DAG). This is essentially a reduction operation, from a list to a single value.

We have two hypotheses for reduction.

One is specifying the same TENSOR (non TENSORLIST) key both in input and in output, in the presence of a TENSORLIST input.
```
SCRIPTRUN s acc_std FOREACH a_list INPUTS a_list c OUTPUTS c
```
the `acc_std` will be ran multiple times, each time passing `c` (the accumulated std) in input.

While this design is clean, it will be less efficient, because won't take advantage of vectorization (although it won't require allocation and copying).
Using the CONCAT argument, we can instead concatenate the list into a tensor (inserting a 0-th dimension) prior to passing it to a model or script.
```
SCRIPTRUN s acc_std CONCAT a_list INPUTS a_list OUTPUTS c
```

### Conclusion

The above design will address all the above requirements, and provide new building blocks for uncertainty estimation from outputs, MCDropout as well as ensembling.

**Comment by filipecosta90** [comment]
@lantiga, as we've discussed, start by adding the features on top on a list of blob tensors and then ( if required by performance reasons ) change to a specific data-structure. in that manner, we leverage redis data structures and don't spend time implementing the new data structure.

**Comment by lantiga** [comment]
So, commands:
- AI.TENSORLIST foo SIZE 100: initializes a RedisList with two elements
  > 1: a magic number ('TENSORLIST'?), to recognize it as an actual tensor list
  > 2: the SIZE
- AI.TENSORPOP foo INTO bar
- AI.TENSORPUSH foo FROM bar
- AI.TENSORCONCAT foo INTO bar

Plus, extra args to MODELRUN and SCRIPTRUN
- REPEAT 100
- FOREACH a_list
- FOREACHPOP a_list

I think that's it, what do you think @filipecosta90 ?

**Comment by filipecosta90** [comment]
@lantiga @itamarhaber what do you think of the following API proposal? ( we would basically use lists underneath and the first position of the list would always contain the metadata (all transparent to the user) ). This implies no added data structure and out of the box serialization.


## AI.LSET
```
AI.LSET <key> TENSOR data_type shape1 [shape2 ... ]
```
(write)
Creates an empty tensor list. all list elements ( tensors) have the same type and dimensions. 
**Return value:** A simple 'OK' string or an error. ( same as tensorset )

## AI.LINFO
```
AI.LINFO <key> META
```
(read only)
This is an introspection command used in order to retrieve different information about the streams and associated consumer groups. For now only `META` forms is possible and has the same format as TENSORGET META.


## AI.LINDEX
```
AI.LINDEX list index
```
(read only)
Returns the tensor blob element at index index in the list stored at key. The index is zero-based, so 0 means the first element, 1 the second element and so on. Negative indices can be used to designate elements starting at the tail of the list. Here, -1 means the last element, -2 means the penultimate and so forth.

When the value at key is not a list, an error is returned.
**Return value:** :Bulk string reply: the tensor BLOB value of the requested element,  or nil when index is out of range.


## AI.LPOP
```
AI.LPOP list
```
(read/write)
Removes and returns the first element of the list stored at key.
**Return value:** Bulk string reply: the tensor BLOB value of the first element, or nil when key does not exist.

## AI.RPUSH
```
AI.RPUSH list blob1 [blobn ...]
```
(write)
Insert all the specified tensor blobs at the tail of the list stored at key. If list does not exist an error is returned.
It is possible to push multiple elements using a single command call just specifying multiple arguments at the end of the command. 
**Return value** Integer reply: the length of the list after the push operation.

**Comment by lantiga** [comment]
It’s a good API, I’d also add CONCAT

**Comment by itamarhaber** [comment]
I like where this is going :)

> It’s a good API, I’d also add CONCAT.

`AI.TLCONCAT <source-key> [....] <dest-key>` perhaps?

> I’d like to retain the FROM/INTO forms too.

Why? This very SQL-ish and not Redis List-ish.

> Also, we need a way to atomically clear a list, or pop in bulk.

`AI.TLPOP <key> [<count> | ALL]` maybe?

misc:
* As this is turning into a design doc, perhaps we should maintain one instead of bickering over an issue?
* These aren't just lists but rather tensor lists so let us settle on AI.TL* (for now ;))

**Comment by lantiga** [comment]
@itamarhaber I like the TL prefix!

> Why? This very SQL-ish and not Redis List-ish.
Because I'd like to get a TENSOR from a TL or push a TENSOR to a TL, but avoid the roundtrip. Since a tensor is typically bulky, and a list of tensors is even more, I think this could be quite useful.

> AI.TLPOP <key> [<count> | ALL] maybe?
I like it!

> As this is turning into a design doc, perhaps we should maintain one instead of bickering over an issue?
It's a good idea

**Comment by hhsecond** [comment]
Chiming in with few thoughts
- TL prefix is nice
- Re: FROM-INTO form -> If that's not Redis like, perhaps TLPOP and TLPUSH inside DAG
- `AI.TLPOP key [count | ALL]` -> wouldn't this pop all the elements in the list and return it and wouldn't that be unnecessary if the user only wants to clear the list?

**Comment by lantiga** [comment]
Working on a new design involving extending SCRIPT to support calling into `redisai.modelrun`. This allows a lot more flexibility and support models that need to be called iteratively, like GPT2 for text generation.

**Comment by lantiga** [comment]
Superseded by #389
