### ISSUE TITLE
retrocompatibility CI tests for rdb loading

### ISSUE THREAD

**Issue by filipecosta90** [RedisAI/RedisAI#311]
must include
- v0.1
- v0.2
- v0.3
- v0.9

**Comment by lantiga** [comment]
Hi @filipecosta90, are we sure we want to go back that much?

**Comment by filipecosta90** [comment]
probably not @lantiga :) do you think 0.3 and 0.9 are enough?

**Comment by lantiga** [comment]
I was thinking 0.9 :-) But if we think 0.3 is worth, let's support it.

**Comment by lantiga** [comment]
Closed with #313
