### ISSUE TITLE
How to use Redis AI with multiple (different) pytorch models?

### ISSUE THREAD

**Issue by antocapp** [RedisAI/RedisAI#344]
Hello, thanks for this wonderful project.

Is there a way to use RedisAI to deploy multiple different pytorch models (whose input tensors are independent, so input tensor of modelA is completely independent of modelB and viceversa), thus leading to the possibility of a concurrent execution of inferences?

Thanks

**Comment by hhsecond** [comment]
Hi @antocapp 
If I understood your question correctly; yes you can use RedisAI to serve multiple models (regardless of which framework they were built with). You just need to make sure the key names are different for different models and the input/output tensors. I made a quick gist by modifying the example repo code. Let me know if this doesn't help
https://gist.github.com/hhsecond/dd3b7d50ceaef7a7630853b0e8dd7e65

PS: It's recommended to use the [forum](https://forum.redislabs.com/c/modules/redisai) for asking questions. That helps us reserving GitHub issues for issues and feature requests

PSS: I am closing this issue for now. Feel free to re-open if you face issues or please open a thread in the forum in case you have questions. Happy coding

**Comment by antocapp** [comment]
Hi @hhsecond thanks a lot for your support, this solution is indeed very helpful.

I would like to ask you another question: it is possibile, given a torch model (scripted with torch.jit.script and saved with ml2rt), and being this model composed of two methods (one is the classic "forward" method of pytorch nn.Module, while the other is a custom method that I wanted to include into the script with the decorator @torch.jit.export), now given this situation, how can I infer a tensor on RedisAI though the latter method, and not through the forward method? 

Thank you very much, I really appreciate your support.
