### ISSUE TITLE
ERR wrong number of arguments for 'AI.SCRIPTSET' command

### ISSUE THREAD

**Issue by dengliming** [RedisAI/RedisAI#348]
version：0.9.0

```
127.0.0.1:6382> AI.SCRIPTSET myscript CPU TAG myscript:v0.1 SOURCE "return 1"
(error) ERR wrong number of arguments for 'AI.SCRIPTSET' command
```

**Comment by filipecosta90** [comment]
hi there @dengliming , between 0.9.0 and the current master ( soon to be part of a newer version of redisai ) we've added functionalities like the tagging the script and enforced the `SOURCE` keyword.
For 0.9, if you run:
```
$ redis-cli AI.SCRIPTSET myscript CPU "return 1"
(error) expected def but found 'return' here: at <string>:1:0 return 1 ~~~~~~ <--- HERE
```
You should see the error that is expected given that `return 1` is not a valid script. 

--- 
# while we wait for a new release 

While the release is being baked, can you use the `redisai:edge` docker tag?
```
docker run -p 6379:6379 redisai/redisai:edge
```
Also, we've majorly bumped the documentation. The scripting intro should give a good insight on it:
https://oss.redislabs.com/redisai/intro/#scripting

Nice to see you here =)

**Comment by dengliming** [comment]
Got it. Thank you very much. closing.
