### ISSUE TITLE
Add CONFIG command for configuring/loading backends

### ISSUE THREAD

**Issue by lantiga** [RedisAI/RedisAI#36]
Supporting multiple backends (and multiple versions of a backend, e.g. CPU-only, CUDA etc) will have to happen on a dynamic configuration basis, using a `CONFIG` command.

For instance, if we're not using TF, there's no point in loading the libraries or the CUDA kernels.

One tricky part could be unloading, so for the first iteration we wouldn't go back after a load.

TorchScript support could be loaded by default, but we'll need to decide what happens if the default is CPU-only and we then request CUDA `libtorch` support.

So at first we would require a `CONFIG` command even for basic script support (i.e. no backend would be loaded by default).

**Comment by hhsecond** [comment]
@lantiga @K-Jo What do you think the best way of distributing Docker images in this case. We can definitely support docker images for each backend separately but we should support a single image with all the backends as well (we can let the user load it dynamically but we probably need to install all the required CUDA versions beforehand).

**Comment by lantiga** [comment]
@hhsecond Good point. I think having different container images for each backend is a bit overkill and in any case it could limit what users can do (the PyTorch backend is needed for SCRIPT, etc).
I'd rather build at most 3 images:
- all CPU
- TF GPU, TORCH GPU, ONNX CPU 
- all GPU (with CUDA 9.0 + 9.1)

**Comment by gkorland** [comment]
@mnunberg @MeirShpilraien can you please see if you can help

**Comment by lantiga** [comment]
FYI, @MeirShpilraien helped me and the issue is now solved.

**Comment by andresrinivasan** [comment]
> @hhsecond Good point. I think having different container images for each backend is a bit overkill and in any case it could limit what users can do (the PyTorch backend is needed for SCRIPT, etc).
> I'd rather build at most 3 images:
> 
> * all CPU
> * TF GPU, TORCH GPU, ONNX CPU
> * all GPU (with CUDA 9.0 + 9.1)

When we add TPU and AMD GPU would that go in #2 and #3?

**Comment by lantiga** [comment]
@andresrinivasan these would be specific enough to warrant separate containers IMHO

**Comment by lantiga** [comment]
Closed by #159

**Comment by lantiga** [comment]
Let's keep the comments in mind for packaging
