### ISSUE TITLE
torch jit compiler crashes when defaults arguments to script functions lack type hints

### ISSUE THREAD

**Issue by DvirDukhan** [RedisAI/RedisAI#371]
having a function with default parameters in torch script crashes the compiler and Redis server due to bad access error. The exception is not caught in the try-catch block.

**Comment by filipecosta90** [comment]
> having a function with default parameters in torch script crashes the compiler and Redis server due to bad access error. The exception is not caught in the try-catch block.

dvir can you share a quick sample ? =) we can integrate on tests right away

**Comment by lantiga** [comment]
I think this may actually be a bug on the libtorch side.

**Comment by DvirDukhan** [comment]
it is in the libtorch. do you want me to open them an issue? https://github.com/pytorch/pytorch/issues

**Comment by lantiga** [comment]
Let me take a look and ask someone from the core team

**Comment by lantiga** [comment]
So, a bit more context.

Syntax can be wrong, RedisAI doesn't crash but reports the error, however:
default parameters that are *not type-annotated* crash the interpreter.

So basically:
```
def foo(a, b=1):
    return a
```
crashes, but
```
def foo(a, b:int = 1):
    return a
```
doesn't crash and actually succeeds.

There's nothing we can do in RedisAI but I'm trying to work at getting this fixed upstream.

**Comment by lantiga** [comment]
I have a fix in the PyTorch TorchScript interpreter: I'm going to open a PR shortly, hopefully it will be merged soon. I'll reference it here for us to track progress.

**Comment by lantiga** [comment]
https://github.com/pytorch/pytorch/pull/39021

**Comment by lantiga** [comment]
The patch has been merged:
https://github.com/pytorch/pytorch/commit/e088902b4a8cd7ea1dd998e6ed7d523786aca304

We'll be good with the next PyTorch release.

**Comment by lantiga** [comment]
With #485 merged, we can close this issue.
