### ISSUE TITLE
AI.SCRIPTRUN results are being replicated twice

### ISSUE THREAD

**Issue by filipecosta90** [RedisAI/RedisAI#382]
The results are being replicated on `RAI_ModelRunScriptRunReply` via `RedisAI_ReplicateTensorSet` and via `RedisModule_ReplicateVerbatim` within `RedisAI_ScriptRun_RedisCommand`. 
I believe the call that should be removed is the `RedisModule_ReplicateVerbatim` given that `RedisAI_ReplicateTensorSet` will ensure determinism on slves in cases of on determisitic outputs ( like we have on modelrun )

**Comment by lantiga** [comment]
Yes, I agree. This is a leftover from the times when SCRIPT was not managed by the queue.
