### ISSUE TITLE
It seems do not support sklearn？

### ISSUE THREAD

**Issue by MrRace** [RedisAI/RedisAI#393]
By now it seems do not support traditional machine learning models, for example models in sklearn. Is it?

**Comment by lantiga** [comment]
Hi @MrRace it actually does, thanks to the ONNXRuntime backend, which supports the ONNX-ML specification.

Take a look at https://github.com/RedisAI/redisai-examples/tree/master/models/sklearn
for learning how to export sklearn models to ONNX-ML and https://github.com/RedisAI/redisai-examples/blob/master/python_client/ for learning how to run them.

Please get back if you encounter issues or want to know more, closing for now.
