### ISSUE TITLE
TENSORSET should free existing data 

### ISSUE THREAD

**Issue by DvirDukhan** [RedisAI/RedisAI#402]
`RedisAI_TensorSet_RedisCommand` calls to `RAI_OpenKey_Tensor` which validates that the key is empty or is a tensor. After parsing the args it sets the new value in the key, without releasing existing data if there is such.
If the is an unwated byproduct we should have a command like TENSORUPDATE

**Comment by lantiga** [comment]
Actually it does: when a new key is set, `RAI_Tensor_DTFree` is called on the old value (you can verify).
