### ISSUE TITLE
Upgrade TF backend to libtensorflow 2.x 

### ISSUE THREAD

**Issue by lantiga** [RedisAI/RedisAI#418]
Since June 2020 TF has started releasing official `libtensorflow` builds. For now only nightly builds for 2.2.0 are available.
The first official release for libtensorflow 2.x will happen with TF 2.3.0.

A first test shows that `libtensorflow` 2.2.0 is a drop-in replacement in RedisAI, everything just works. We will need to take care of the packaging.

**Comment by lantiga** [comment]
Tensorflow 2.3 has been released.

AFAIK, libtensorflow still ships nightlies regularly, but I couldn't find an official 2.3.0 cut.

**Comment by gkorland** [comment]
ref #459
