### ISSUE TITLE
Failed DAGRUN with redis cluster

### ISSUE THREAD

**Issue by mellis13** [RedisAI/RedisAI#476]
# Description
Hello, 
We ( @Spartee ) are investigating RedisAI on our clusters to perform inference at scale. We have everything working on a single instance of Redis with RedisAI, but are running into challenges using RedisAI with Redis clusters.  Specifically, we are trying to understand how ``DAGRUN`` should work when the input tensor and model are on different nodes.  Is  ``DAGRUN`` supposed to be compatible with redis clusters?  What is the expected behavior of ``DAGRUN`` with Redis clusters when the model, input, and output are on different nodes?

As an example of the challenge that we are seeing, when using the bash client (see commands below), if the server where the model exists is addressed with the cluster (``-c``) option, then the MOVE redirection will be followed to the input tensor sever, and an ``(error) ERR model key is empty`` error will be received because the input tensor is not on the same server as the model.  If the server where the model exists is addressed without the cluster (``-c``) option, then we get an error corresponding to the MOVE redirect command ``(error) MOVED 4881 127.0.0.1:30001``.

Thank you!

# Client Commands
```bash
# Run DAGRUN in cluster mode
redis-cli -c -h 127.0.0.1 -p 30001 -x AI.MODELSET mnist TORCH CPU BLOB < mnist_cnn.pt
redis-cli -c -h 127.0.0.1 -p 30001 -x AI.TENSORSET image FLOAT 1 1 28 28 BLOB < ../data/one.raw
redis-cli -c -h 127.0.0.1 -p 30002
AI.DAGRUN LOAD 1 image PERSIST 1 image_out |> AI.MODELRUN mnist INPUTS image OUTPUTS image_out
```
or
```bash
# Do not run DAGRUN in cluster mode
redis-cli -c -h 127.0.0.1 -p 30001 -x AI.MODELSET mnist TORCH CPU BLOB < mnist_cnn.pt
redis-cli -c -h 127.0.0.1 -p 30001 -x AI.TENSORSET image FLOAT 1 1 28 28 BLOB < ../data/one.raw
redis-cli -h 127.0.0.1 -p 30002
AI.DAGRUN LOAD 1 image PERSIST 1 image_out |> AI.MODELRUN mnist INPUTS image OUTPUTS image_out
```
# Software
- Redis v6.0.3
- RedisAI v1.0.2
- Torch v1.5.1

**Comment by gkorland** [comment]
@mellis13 DAGRUN does support cluster API, but it assumes all the keys and models are located on the same shard.
If have to shard the data/keys across different shards, you have two options:
1. Use Redis Enterprise - in Redis Enterprise the proxy is making sure the models will be broadcast to all the shards while the data will still sharded.
2. Make sure you store the model on all the shards with some `{}` that will make sure you store it on each on of the shards.
e.g. `mymodel` should be stored as `mymodel{1}`, `mymodel{2}`...

**Comment by mellis13** [comment]
@gkorland Thanks for the explanation and suggestions.  I think your solutions will be sufficient for us.  I'll go ahead and close issue.  Thank you!
