### ISSUE TITLE
Crash on AI.MODELSET <key> TORCH CPU BLOB

### ISSUE THREAD

**Issue by valdemaras-pipiras** [RedisAI/RedisAI#478]
Oct 15 17:30:42 srv1 redis[49626]: Redis 6.0.8 crashed by signal: 11
Oct 15 17:30:42 srv1 redis[49626]: Crashed running the instruction at: 0x7f3b9001a975
Oct 15 17:30:42 srv1 redis[49626]: Accessing address: 0x18
Oct 15 17:30:42 srv1 redis[49626]: Failed assertion: <no assertion failed> (<no file>:0)
Oct 15 17:30:42 srv1 redis[49626]: 
                                                      ------ STACK TRACE ------
Oct 15 17:30:42 srv1 redis[49626]: 
                                                      ------ INFO OUTPUT ------
Oct 15 17:30:42 srv1 redis[49626]: [5.1K blob data]
Oct 15 17:30:42 srv1 redis[49626]: 
                                                      ------ CLIENT LIST OUTPUT ------
Oct 15 17:30:42 srv1 redis[49626]: id=60 addr=172.22.107.102:50020 fd=20 name= age=41 idle=1 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=replconf user=default
                                                      id=56 addr=172.22.107.102:48499 fd=15 name=sentinel-c7f3a811-pubsub age=42 idle=1 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe user=default
                                                      id=57 addr=172.22.107.102:59113 fd=16 name=sentinel-c7f3a811-cmd age=42 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping user=default
                                                      id=58 addr=172.22.107.101:33887 fd=17 name=sentinel-6c995a4c-pubsub age=42 idle=1 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe user=default
                                                      id=63 addr=172.22.107.100:57594 fd=24 name= age=37 idle=27 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hincrby user=default
                                                      id=59 addr=172.22.107.101:57525 fd=18 name=sentinel-6c995a4c-cmd age=42 idle=1 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=publish user=default
                                                      id=61 addr=172.22.107.100:52019 fd=19 name=sentinel-12d36fba-cmd age=41 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=info user=default
                                                      id=62 addr=172.22.107.100:46129 fd=21 name=sentinel-12d36fba-pubsub age=41 idle=1 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe user=default
                                                      id=64 addr=172.22.107.100:57604 fd=25 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=1430824 obl=0 oll=0 omem=0 events=r cmd=ai.modelset user=default
Oct 15 17:30:42 srv1 redis[49626]: 
                                                      ------ CURRENT CLIENT INFO ------
Oct 15 17:30:42 srv1 redis[49626]: id=64 addr=172.22.107.100:57604 fd=25 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=1430824 obl=0 oll=0 omem=0 events=r cmd=ai.modelset user=default
Oct 15 17:30:42 srv1 redis[49626]: argv[0]: 'AI.MODELSET'
Oct 15 17:30:42 srv1 redis[49626]: argv[1]: 'ai:model:0'
Oct 15 17:30:42 srv1 redis[49626]: argv[2]: 'TORCH'
Oct 15 17:30:42 srv1 redis[49626]: argv[3]: 'CPU'
Oct 15 17:30:42 srv1 redis[49626]: argv[4]: 'BLOB'
Oct 15 17:30:42 srv1 redis[49626]: [15B blob data]
Oct 15 17:30:42 srv1 redis[49626]: 
                                                      ------ REGISTERS ------
Oct 15 17:30:42 srv1 redis[49626]: 
                                                      RAX:0000000000000000 RBX:000055c1a6604878
                                                      RCX:0000000000000000 RDX:0000000000000000
                                                      RDI:00007ffda0291ce0 RSI:000055c1a6604878
                                                      RBP:00007ffda0291f60 RSP:00007ffda0291ce0
                                                      R8 :0000000000000000 R9 :0000000000000001
                                                      R10:000055c1a58c8010 R11:0000000000000020
                                                      R12:00007ffda0292da0 R13:0000000000000138
                                                      R14:00007ffda0292dc0 R15:00007ffda0292da0
                                                      RIP:00007f3b9001a975 EFL:0000000000010246
                                                      CSGSFS:002b000000000033
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291cef) -> 000055c1a65eb0a0
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291cee) -> 000055c1a65eb0b0
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ced) -> 00000000000000ae
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291cec) -> 000055c1a65eb0a0
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ceb) -> 000055c1a65eb0b0
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291cea) -> 0000000000000000
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce9) -> 00007f3b8dbf7e35
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce8) -> 00007ffda0292c10
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce7) -> 00007ffda0291fa0
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce6) -> 0000000000000000
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce5) -> 00007f3b9001aeee
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce4) -> 00007ffda0292da0
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce3) -> 00007ffda0292dc0
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce2) -> 0000000000000138
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce1) -> 00007ffda0292da0
Oct 15 17:30:42 srv1 redis[49626]: (00007ffda0291ce0) -> 0000000000000000
Oct 15 17:30:42 srv1 redis[49626]: 
                                                      ------ MODULES INFO OUTPUT ------
Oct 15 17:30:42 srv1 redis[49626]: [366B blob data]
Oct 15 17:30:42 srv1 redis[49626]: 
                                                      ------ FAST MEMORY TEST ------
Oct 15 17:30:42 srv1 redis[49626]: Bio thread for job type #0 terminated
Oct 15 17:30:42 srv1 redis[49626]: Bio thread for job type #1 terminated
Oct 15 17:30:42 srv1 redis[49626]: Bio thread for job type #2 terminated
Oct 15 17:31:11 srv1 redis[49626]: Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.
Oct 15 17:31:11 srv1 redis[49626]: 
                                                      ------ DUMPING CODE AROUND EIP ------
                                                      Symbol: (null) (base: (nil))
                                                      Module: /usr/lib64/redis/modules/backends/redisai_torch/lib/libtorch_cpu.so (base 0x7f3b8d0eb000)
                                                      $ xxd -r -p /tmp/dump.hex /tmp/dump.bin
                                                      $ objdump --adjust-vma=(nil) -D -b binary -m i386:x86-64 /tmp/dump.bin
                                                      ------
Oct 15 17:31:11 srv1 redis[49626]:

**Comment by lantiga** [comment]
Hi @valdemaras-pipiras, the current limitation is that TORCH models need to be exported with a PyTorch version that is *equal or lower* than the PyTorch version shipped as RedisAI backend.

Currently we support PyTorch 1.5.0, so you need to export your PyTorch model with PyTorch 1.5.0 or lower.

We will be updating PyTorch to the most current when we release RedisAI 1.2.0 in 2-3 weeks.

**Comment by lantiga** [comment]
@valdemaras-pipiras no rush, but can you let us know if the issue gets solved by exporting from PyTorch <= 1.50?

**Comment by valdemaras-pipiras** [comment]
Hi @lantiga, sorry for the late replay and thanks for a great support!

I just wanted to take a pause until my colleague will re-generate model with PyTorch = 1.5.0.

I will come back to you with the results at once we'll test it.

Thanks one more time!

**Comment by valdemaras-pipiras** [comment]
Hello @lantiga,

I do confirm that model created with PyTorch = 1.5.0 works like a charm.

Thanks for your support!
