### ISSUE TITLE
add support for short reads on RDB

### ISSUE THREAD

**Issue by DvirDukhan** [RedisAI/RedisAI#486]

**Comment by lantiga** [comment]
Hey @DvirDukhan, can you provide a few more details on short reads?

**Comment by DvirDukhan** [comment]
@lantiga 
When in a primary<->replica configuration, when doing full sync the RDB is streamed to the replica (diskless sync). During that, the primary might crash, so the replica will not get all the data and cause an invalid read (short read). Redis can recognize such a situation and have a graceful cancelation of the sync on the replica, without crashing it, if the module tells Redis it is applicable to it.
