### ISSUE TITLE
Refactor RUN SET GET commands

### ISSUE THREAD

**Issue by lantiga** [RedisAI/RedisAI#49]
The suggested idea is to concentrate all the backend-specific stuff (NAMES included) in the AI.SET GRAPH command; 
This way if a client or RedisAI's codebase that calls RUN into a TensorFlow model can change the model underneath into a PyTorch model instead without having to update the code.  The model can be updated by calling AI.SET, and all the AI.RUN commands will be unmodified.

RUN will be defined as
`AI.RUN GRAPH key INPUTS key1 key2 OUTPUTS key2 key2`
As for keeping `GRAPH` or `SCRIPT` in there, we could drop it because we can know the underlying type at the key
However, the rest of the API has GRAPH and SCRIPT set explicitly.
Also, the SCRIPT signature has the name of the function as an extra argument, so technically it would be better to have the subcommand set explicitly

```
AI.SET GRAPH key backend device [INPUTS name1 name2] [OUTPUTS name1 name2] BLOB graphBlob
```

```
AI.SET TENSOR tensor_key data_type DIMS dim1..dimN (BLOB data | VALUES ..)
```

```
AI.GET TENSOR source VALUES

1) INT32
2) (integer) 3           # remove this
3) 1) (integer) 2
   2) (integer) 2
   3) (integer) 1
4) (integer) 16         # remove this
5) 1) (integer) 721487365
   2) (integer) 168643407
   3) (integer) 658688
   4) (integer) 32554
```

**Comment by K-Jo** [comment]
I like the approach of having the AI.RUN agnostic of the underlying model.

In addition I think we need a more simple interface to divide logic from tensors.

```sh
AI.SETTENSOR tensory_key ...
AI.GETTENSOR tensory_key ...
```
since there is no GET alternative on a script/graph.

**Comment by gkorland** [comment]
@K-Jo there should be AI.SET/GET GRAPH

**Comment by lantiga** [comment]
We have a final decision to make: do we go with
```
verb (command) + object (subcommand)
```
or
```
verbobject (command)
```

Like
```
AI.SET GRAPH
AI.RUN GRAPH

AI.SET SCRIPT
AI.GET SCRIPT
AI.RUN SCRIPT

AI.SET TENSOR
AI.GET TENSOR
```
or
```
AI.SETGRAPH
AI.RUNGRAPH

AI.SETSCRIPT
AI.GETSCRIPT
AI.RUNSCRIPT

AI.SETTENSOR
AI.GETTENSOR
```

Note that from an implementation standpoint it doesn't literally change anything (it's not more complex to have a subcommand to dispatch on the object type).

From a documentation standpoint, though, if one groups docs by command, as done usually in Redis, it might be confusing to see what the commands do with command + subcommand, since the behavior (and syntax) is specified by subcommands.

Last option: object first, verb last (many Redis commands are this way, although it doesn't necessarily mean we should do the same here; at some point we also tried with `GSET GRUN SSET SGET SRUN TSET TGET`, etc, but in my opinion user code ended up being very obscure):
```
AI.GRAPHSET
AI.GRAPHRUN

AI.SCRIPTSET
AI.SCRIPTGET
AI.SCRIPTRUN

AI.TENSORSET
AI.TENSORGET
```

Votes?

**Comment by lantiga** [comment]
This is the last round of changes before it's final. I'd like to have the refactor complete and final by Friday Jan 15.

**Comment by K-Jo** [comment]
There could be a fourth, hybrid option.  You consider a tensor as a datatype and align it with Redis.  Same goes for the Graph and the Script, but the Run command you keep separate.

```
AI.TENSORSET
AI.TENSORGET

AI.GRAPHSET

AI.SCRIPTSET
AI.SCRIPTGET  // do we really need this one?

AI.RUN GRAPH|SCRIPT
```

THE VOTES ARE OPEN!!!
Option 1:  
```
verb (command) + object (subcommand)
```
Option 2
```
verbobject (command)
```
Option 3:
```
objectverb (command)
```
Option 4 Hybrid:
For Data
```
objectverb (command)
```
For execution
```
verb (command) + object (subcommand)
```

THE VOTES ARE OPEN!!!

**Comment by gkorland** [comment]
I think we should go with 
```
AI.GRAPHSET
AI.GRAPHGET
AI.GRAPHRUN

AI.SCRIPTSET
AI.SCRIPTGET
AI.SCRIPTRUN

AI.TENSORSET
AI.TENSORGET
```

**Comment by lantiga** [comment]
Votes from @itamarhaber @MeirShpilraien @K-Jo ? 🍿

**Comment by K-Jo** [comment]
Pardon my ignorance, but why do we need a GET on graph and script?

**Comment by lantiga** [comment]
I'd say mostly for introspection: the GRAPHGET could return a sha of the protobuf, so you can check whether the graph at the key is the graph you're expecting.
On the same lines, the GET on script could return the full script or a sha (it return the full script right now, I'd keep it that way).

**Comment by MeirShpilraien** [comment]
In my opinion we should go with 
```
AI.GRAPHSET
AI.GRAPHRUN

AI.SCRIPTSET
AI.SCRIPTGET
AI.SCRIPTRUN

AI.TENSORSET
AI.TENSORGET
```

**Comment by lantiga** [comment]
So it looks like we have a winner? I like that too, btw.

**Comment by K-Jo** [comment]
@lantiga @gkorland One last discussion to be held here.  Apologies!  Is there any objection renaming Graph to Model?  If we think in a broader context, we plan to add the OMNIX support for ML models, which would allow a further abstraction of an
```
AI.MODELRUN
```
command

**Comment by lantiga** [comment]
I’m not opposed to this, you have a good point with ML.

Others?

**Comment by gkorland** [comment]
:+1:

**Comment by K-Jo** [comment]
Ok Here's the final list
```sh
AI.MODELSET
AI.MODELRUN

AI.SCRIPTSET
AI.SCRIPTGET
AI.SCRIPTRUN

AI.TENSORSET
AI.TENSORGET
```

**Comment by lantiga** [comment]
Reopening the issue just so we can link a PR to it.

**Comment by lantiga** [comment]
#52 has been merged, so closing
