### ISSUE TITLE
CI issues

### ISSUE THREAD

**Issue by DvirDukhan** [RedisAI/RedisAI#504]
- [x] Add Valgrind
- [ ] Build an entire build matrix on PR upon trigger
- [ ] Relase matrix - {platform}-{GPU}
  - [ ] Platforms - Jetson, mac, and the the entire combination of
    - [ ] Arch - x86_64(AMD), x86_64_MKL_AIX-512 (intel), arm
    - [ ] OS - ubuntu16, unbutu18, ubuntu20, Centos7
  - [ ] GPU - CPU(no-gpu), CUDA10.1-cudnn8, CUDA10.2-cudnn8, CUDA11.1-cudnn8

@rafie what do you think?

**Comment by rafie** [comment]
valgrind - easy.
Build entire matrix: we currently build Linux platforms on master, but anything but bionic will fail because we do not build backends for those platform. But I'm taking care of this, and we'll be able to build+test the matrix when it's ready.

**Comment by DvirDukhan** [comment]
see #591
