### ISSUE TITLE
DAGRUN output tensor names not binary string safe

### ISSUE THREAD

**Issue by mellis13** [RedisAI/RedisAI#508]
Hello,

I have been doing some work with DAGRUN, and I encountered a problem when the output tensor name contains a 0 value.  For example, the following set of commands using the redis-CLI will not persist the correct key value (everything after the 0 value seems to be ignored).

```
redis-cli -c -h 127.0.0.1 -p 6379 -x AI.MODELSET mnist_1 TORCH CPU BLOB < mnist_cnn.pt
redis-cli -c -h 127.0.0.1 -p 6379 -x AI.TENSORSET "image" FLOAT 1 1 28 28 BLOB < one.raw
redis-cli -c -h 127.0.0.1 -p 6379
AI.DAGRUN LOAD 1 image PERSIST 1 "{\x00\x00}.output" |> AI.MODELRUN mnist_1 INPUTS image OUTPUTS "{\x00\x00}.output"
```

![keys_inventory](https://user-images.githubusercontent.com/4109943/100018448-571da300-2d91-11eb-9cfb-71882863e33f.png)

If this error can be reproduced, would it be possible to make the ``PERSIST`` action binary string safe?   In general, it seems like all of the other RedisAI commands are binary string safe.  Thank you!

**Comment by lantiga** [comment]
Merged!
