### ISSUE TITLE
Unit test framework

### ISSUE THREAD

**Issue by alonre24** [RedisAI/RedisAI#517]
Fix the google test framework in RedisAI project and check for the following:

- [ ] Error handling when a device run queue isn't created properly before DAG run execution.

- [ ] Async DAG run LLAPI is enabled with a user-defined DAG run_info and OnFinish callback.

**Comment by DvirDukhan** [comment]
@alonre24 can we close this?

**Comment by alonre24** [comment]
I think so.... closing
