### ISSUE TITLE
Expose model inputs and outputs number in `AI.MODELGET`

### ISSUE THREAD

**Issue by DvirDukhan** [RedisAI/RedisAI#529]
As `INPUTS` and `OUTPUTS` are required only for TF models in the `AI.MODELSET` command, we want to allow investigate model's input and outputs:

- [ ] ONNX:
```
 size_t n_input_nodes;
 ort->SessionGetInputCount(session, &n_input_nodes);
 size_t n_output_nodes;
 ort->SessionGetOutputCount(session, &n_output_nodes);
```

- [ ] Torch - User defined

**Comment by nishantgeorge** [comment]
I think `AI.MODELGET` might be more appropriate since it already returns information about the model's inputs, and `AI.INFO` does not.
