### ISSUE TITLE
docker command update from `redislabs/redisai` to `redisai/redisai`

### ISSUE THREAD

**Issue by ThomAub** [RedisAI/RedisAI#673]
Hello, 
I try to follow the readme but I was not able to pull the image with the `docker run -p 6379:6379 redislabs/redisai:latest` looking at docker hub I saw that this maybe moved to redisai/redisai ? 
If this is correct I can try to point to where it appears in the documentation ?

**Comment by chayim** [comment]
@ThomAub The latest **edge** push of RedisAI can be found with edge-cpu and edge-gpu tags at https://hub.docker.com/r/redislabs/redisai/tags?page=1&ordering=last_updated.

I'll update the documentation accordingly.

**Comment by ThomAub** [comment]
@chayim ok I will use this ! 
Thanks for this fast answer I'm eager to play a bit with RedisAI :)

**Comment by chayim** [comment]
My pleasure, good luck. This is literally the bleeding edge ;)
