### ISSUE TITLE
Tensor values shouldn't be returned strings but as numbers

### ISSUE THREAD

**Issue by gkorland** [RedisAI/RedisAI#69]
```
127.0.0.1:6379>  AI.TENSORGET source VALUES
1) FLOAT
2) 1) (integer) 2
   2) (integer) 2
3) 1) "1.1000000238418579"
   2) "2.0999999046325684"
   3) "3.0999999046325684"
   4) "4.0999999046325684"
```

**Comment by lantiga** [comment]
Hi @gkorland, I'm using `RedisModule_ReplyWithDouble` correctly, I think, see:
https://github.com/RedisAI/RedisAI/blob/master/src/redisai.c#L366

The thing is that the current Redis protocol doesn't support floating point values, so they get coerced into strings when returned. In contrast, VALUES from an integer tensor works with integer types as expected.

So there isn't much we can do about this AFAIK, other than waiting for RESP v3 :-)

**Comment by lantiga** [comment]
Closing now, feel free to reopen @gkorland
