### ISSUE TITLE
Can not do inference in a redis transaction

### ISSUE THREAD

**Issue by donchev7** [RedisAI/RedisAI#726]
Hi,

maybe I am doing something wrong but what is the general flow of doing a prediction / inference execution with redisAI?

When I do:

```
MULTI
AI.TENSORSET key ...
AI.MODELRUN modelName INPUTS key OUTPUT outputKey
AI.TENSORGET outputKey VALUES
EXEC
```

I get an error telling me AI.MODELRUN does not support to be wrapped inside a transaction:

```
ReplyError: ERR Cannot run RedisAI command within a transaction or a LUA script
```

My question is, how do I take care of race conditions if the **key** and **outputKey** are const?

My workaround is to use random suffixes for **key** and **outputKey** every time my server does a prediction. But how do I delete those tensors once I am done?

**Comment by DvirDukhan** [comment]
you can do it with a DAG context https://oss.redislabs.com/redisai/master/commands/#aidagrun
```
AI.DAGRUN 
|>
AI.TENSORSET inputTensorName ...
|>
AI.MODELRUN modelName INPUTS inputTensorName OUTPUT outputTensorName
|>
AI.TENSORGET outputTensorName VALUES
```
Note that in the next week we will deprecate `DAGRUN` command and introduce `DAGEXECUTE`. The `DAGRUN` command will still be available but not recommended to use.
