### ISSUE TITLE
Quick start guide is incomplete

### ISSUE THREAD

**Issue by hhsecond** [RedisAI/RedisAI#82]
I understand it's under development. Certain things I found good-to-have in the document is mentioning about the command line arguments to `get_deps.sh`, pre-requisites for `get_deps.sh` to work such as 	- unzip, cmake, g++, redis server, GPU/CPU etc. Perhaps our shell script could give a warning before it starts the execution. I could give a PR, if these are not written yet

**Comment by K-Jo** [comment]
https://github.com/RedisAI/RedisAI/blob/master/Dockerfile#L3 and https://github.com/RedisAI/RedisAI/blob/master/Dockerfile#L6
These two should help list the dependencies.  There is no such minimum requirements in the make, can you assist @hhsecond ?

**Comment by hhsecond** [comment]
@K-Jo As far as we promote docker build as the primary way of setting up RedisAI (this wasn't the case when I raised the issue and I thought we should have it in the shell script), this sounds perfect. I am closing this issue then.
