### ISSUE TITLE
MTENSORGET

### ISSUE THREAD

**Issue by manugarri** [RedisAI/RedisAI#834]
**Is your feature request related to a problem? Please describe.**
At my company we run slow feature embedding generation as a batch process periodically.  We are considering redisai to store those so we dont have to compute the embeddings at run time.

However at run time we require loading up 1000s of those embedings from RedisAI. Right now the only way i see i can do it is like this:

```
def get_embedding(id):
    try:
        return redisai.tensorget(d)
    except ResponseError:
        return None    
```

However this process is pretty slow as it queries a key at a time.

**Describe the solution you'd like**
Ideally MGET would be implemented for tensors (so MTENSORGET i guess), so i would be able to do:

```
#Thousands of IDs
ids = [id1,id2,....]

embeddings = redisai.mtensorget(ids)
```

**Describe alternatives you've considered**
Since redis clients are thread safe in python my alternative option is to use multithreading to return multiple tensors at once.

**Comment by esandoval30** [comment]
Thanks, @manugarri  - We'll add this feature to our backlog. We should start work on it once RedisAI 1.2.5 is released (targeting late Sept/Early Oct 2021).

In the meantime, there is a (rather complex) workaround which would involve RedisGears (another Redis module).  If you need this urgently, let us know and we can guide you

**Comment by SDesch** [comment]
Or you could use a regular redis library (such as [https://github.com/andymccurdy/redis-py](https://github.com/andymccurdy/redis-py)) and issue your individual `TENSORGET` commands in a single go using pipelining.

**Comment by manugarri** [comment]
Thanks @esandoval30, looking forward to it, for now Im using ThreadPoolExecutor in python and seems to work pretty well.

@SDesch  One thing that stops me from using a pipe is that currently redisai-py throws an exception when a key is not found (versus regular redis client that returns None) and this means i cant directly call redisai commands and I have to catch them.

**Comment by SDesch** [comment]
@manugarri I'd just write a small function that wraps the redis call and raises when the result is `None` as this is far simpler that using threads (and will have a better performance)

**Comment by manugarri** [comment]
@SDesch this is what i am doing.

But then there is no point in doing a pipe, right? since the exception will happen at the pipe.get time and not when the `execute` happens.

Maybe you can provide an example?

**Comment by SDesch** [comment]
Dunno what you expect to happen when you request a tensor that does not exist along with some that do but maybe something like

```python

def get_multiple_tensors(redis, *keys):
    pipeline = redis.pipeline()
    for key in keys:
        pipeline.execute_command('AI.TENSORGET', key) # just queues the commands
        
    results = pipeline.execute() # fetches all the queued results
    
    missing_tensors = [key for key, result in zip(keys, results) if result is None]
    
    if missing_tensors:
        raise ValueError(f'{missing_tensors} are missing')  # or some other error checking of your choice 
    else:
        return {key: result for key, result in zip(keys, results)}
        
```

**Comment by manugarri** [comment]
this is a brief implementation of what im doing btw, any improvements would be more than welcome

```
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from redisai import Client
from redis import ResponseError

N_WORKERS = 16  #number of threads

product_ids = ['id1', 'id2',...]
redisai = Client(host=redis_host, port=redis_port, password=redis_pwd)
product_embeddings = []
failed_keys = []    

def get_embedding(product_id):
    try:
        return redisai.tensorget(product_id)
    except ResponseError:
        return None        
    

with tqdm(total=len(product_ids)) as pbar:
    with ThreadPoolExecutor(max_workers=N_WORKERS) as executor:
        # Using a dict for preserving the downloaded file for each future, 
        #to store it as a failure if we need that
        futures = {
            executor.submit(get_image_embedding, p): p for p in data
        }
        for future in as_completed(futures):
                result = future.result()
                if  isinstance(result, np.ndarray):
                    product_embeddings.append([futures[future],result])
                else:
                    failed_keys.append(futures[future])
            pbar.update(1)
```

**Comment by manugarri** [comment]
@SDesch thanks for your example, however, as I mentioned before , executing in a pipe wont work because it throws an exception

```
ResponseError: Command # 1 (AI.TENSORGET 2f2e213a6cdd21615117a615dc798288798.) of pipeline caused error: tensor key is empty or in a different shard
```

**Comment by SDesch** [comment]
@manugarri uh that sucks:/ imho this is somewhat of a design flaw in the python redis library as instead of raising `ResponseError` it would be better to just return the `hiredis.ReplyError` it gets. The docs sadly don't go into much detail about this and spelunking in the code I could not find a way to tell `redis-py` to just return errors.

**Comment by DvirDukhan** [comment]
@manugarri are all your tensors in the same shape? If so, you can use a script in order to append them together and return the batched tensor
Tell me if this option is valid to you so I can write a small "how-to"
