### ISSUE TITLE
[Documentation] AI.SCRIPTSTORE example references AI.SCRIPTSET

### ISSUE THREAD

**Issue by billschereriii** [RedisAI/RedisAI#900]
**Describe the bug**
The documentation for the AI.SCRIPTSTORE example at https://oss.redis.com/redisai/commands/#aiscriptstore references the wrong command:

```
cat addtwo.py | redis-cli -x AI.SCRIPTSET myscript CPU TAG myscript:v0.1 ENTRY_POINTS 1 addtwo SOURCE
                             ^^^^^^^^^^^^
```
Given that the parameters to the command are the new ones for AI.SCRIPTSTORE and not the parameters for AI.SCRIPTSET, this is clearly a missed update.

**Expected behavior**
Examples should match the command

**Environment (please complete the following information):**
Any web browser

**Comment by DvirDukhan** [comment]
thanks @billschereriii 
I submitted #901 for fixing it
