### ISSUE TITLE
AI.CONFIG MODEL_CHUNK_SIZE fails on Redis clusters

### ISSUE THREAD

**Issue by billschereriii** [RedisAI/RedisAI#908]
**Describe the bug**
AI.CONFIG MODEL_CHUNK_SIZE fails when called in clustered Redis environments.

**To Reproduce**
1. Set up a local Redis cluster of three nodes
2. Compile and execute the code below (requires hiredis)
3. Vary the shard connected to by changing the port parameter in the call to `redisConnect()` in line 6.
4. Observe that for one port, the result is `ok` but for others it is in the form `MOVED 2457 127.0.0.1:6379` 

```cpp
#include <stdio.h>
#include "hiredis.h"

int main(int argc, char **argv)
{
    redisContext *ctx = redisConnect("127.0.0.1", 6380);
    if (ctx == NULL || ctx->err) {
        printf("Connection failed\n");
        return -1;
    }

    redisReply *reply = redisCommand(ctx, "AI.CONFIG MODEL_CHUNK_SIZE %d", 1024 * 1024);
    if (reply == NULL) {
        printf("Command failed (%d): %s\n", ctx->err, ctx->errstr);
        return -1;
    }
    else {
        printf("Command succeeded!\n");
        printf("reply: %s\n", reply->str);
    }
    freeReplyObject(reply);
    redisFree(ctx);

    return 1;
}
```

**Expected behavior**
We would expect the command to work correctly, independently of which shard it is sent to.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: ubuntu 20.04, MacOS
 - Version 1.2.3
 - Platform x86
 - Runtime CPU -- assume it doesn't matter

**Additional context**
 - We note that AI.CONFIG MODEL_CHUNK_SIZE is not covered in the RedisAI unit tests; nor is it supported in any of the sample clients in the RedisAI Github.
 - We originally ran into this issue when attempting to use the AI.CONFIG info command in SmartRedis, which goes through Redis-plus-plus; the distillation to hiredis above was part of our debugging efforts. The only response from Redis-plus-plus was "2457", which was particularly mystifying.
 - We note that the standard Redis `CONFIG SET` command works perfectly in our code and in the test driver; we speculate that maybe there is a registration issue of some sort with AI.CONFIG?

**Comment by DvirDukhan** [comment]
Thanks @billschereriii 
we will look into it 

related to #907

**Comment by alonre24** [comment]
Hey @billschereriii, I tried to reproduce this bug locally on my machine without success. For all three shards in my cluster, I got:
```
Command succeeded!
reply: OK
```
when running your code.
Can you describe in more details how did you set up your local Redis cluster of three nodes?

In addition,  I can refer you to a unit test in RedisAI that changes `MODEL_CHUNK_SIZE` configuration - https://github.com/RedisAI/RedisAI/blob/master/tests/flow/tests_pytorch.py#L12. Regarding our clients, we plan to have the support in changing this configuration soon (in redisai-py for sure).

**Comment by billschereriii** [comment]
> ~Hey @billschereriii, I tried to reproduce this bug locally on my machine without success. For all three shards in my cluster, I got:~
> 
> ```
> Command succeeded!
> reply: OK
> ```
> 
> ~when running your code. Can you describe in more details how did you set up your local Redis cluster of three nodes?~
> 
> I noticed that I ran with RedisAI latest version (1.2.5), while you ran with 1.2.3. So we found the solution for your issue - run with v1.2.5 and your problem should be fixed :)
> 
> In addition, I can refer you to a unit test in RedisAI that changes `MODEL_CHUNK_SIZE` configuration - https://github.com/RedisAI/RedisAI/blob/master/tests/flow/tests_pytorch.py#L12. Regarding our clients, we plan to have the support in changing this configuration soon (in redisai-py for sure).

Thanks for the investigation!
I'll upgrade to 1.2.5 and let you know if I'm still seeing the problem. If not, I'll close this issue.

**Comment by alonre24** [comment]
To clarify the issue, the problem was with the way that `ai.config` command was registered to Redis. The `RedisModule_CreateCommand` API allows specifying which arguments of the new command are Redis keys. In v1.2.3, the seconds argument (`MODEL_CHUNK_SIZE` in that case) was mistakenly considered as a key (while in practice, *none* of the command arguments are keys). Redis cluster maps `MODEL_CHUNK_SIZE` into `2457` hash slot, which was located in the shard associated with port `6379`. That is why other shards returned the above error.

**Comment by billschereriii** [comment]
That is 100% consistent with what we were seeing. Thanks for the extended explanation!

**Comment by billschereriii** [comment]
I was not able to confirm this fix as RedisAI no longer builds under MacOS. I tried both branches 1.2.5 and 1.2.6 (which I thought I read had restored support for MacOS). Are there any plans to support MacOS any time in the future?

**Comment by DvirDukhan** [comment]
@billschereriii 
the macOS support is on the master branch. 1.2.5 build scripts are not aligned with macOS build. 1.2.6 is not out yet. Please try building the master branch. See #897 please
