### ISSUE TITLE
Add AI.INFO command

### ISSUE THREAD

**Issue by lantiga** [RedisAI/RedisAI#92]
We should write the equivalent of the Redis `INFO` command, to make it easy to write plugin for Prometheus, Telegraf, etc for monitoring (time to compute, number of requests, memory, state of cuda allocations, etc)

**Comment by lantiga** [comment]
Use Redis module INFO API
```
RedisModule_RegisterInfoFunc
RedisModule_InfoAddSection
RedisModule_InfoBeginDictField
RedisModule_InfoEndDictField
RedisModule_InfoAddFieldString
RedisModule_InfoAddFieldCString
RedisModule_InfoAddFieldDouble
RedisModule_InfoAddFieldLongLong
RedisModule_InfoAddFieldULongLong
```

**Comment by lantiga** [comment]
Decision is still implement `AI.INFO` and replicate the same info using the `INFO` API when Redis 6 is out.

**Comment by lantiga** [comment]
Addressing this in #259

**Comment by filipecosta90** [comment]
@lantiga closing this since it was already merged :+1:
