### ISSUE TITLE
What is the definition of execute_command?

### ISSUE THREAD

**Issue by xianwujie** [RedisAI/RedisAI#935]
hello ,
I want to figure out con.execute_command(), but I can't find the definition of this function.
can you help me?

**Comment by DvirDukhan** [comment]
hi @xianwujie 
this is redis-py function to execute a redis command
https://redis-py.readthedocs.io/en/stable/connections.html?highlight=execute_command#redis.Redis.execute_command

**Comment by xianwujie** [comment]
hi @DvirDukhan 
Thanks for your reply, it's very useful
