### ISSUE TITLE
[FR] Expose RAI_Error API

### ISSUE THREAD

**Issue by itamarhaber** [RedisAI/RedisAI#96]
As the returned error RAI_Error* struct is opaque, it requires getters, an initializer and a destructor.

**Comment by mnunberg** [comment]
Initializer: `={0}`
destructor: `RAI_ClearError()`

**Comment by itamarhaber** [comment]
@mnunberg 

These are available in err.h, not in redisai.h. Besides, the struct may change in the implementation, so a formal API to get the error is needed imo.

**Comment by mnunberg** [comment]
I think for a public API it’s probably best to just expose a string. I wasn’t aware we had an extension API yet :)

**Comment by lantiga** [comment]
Addressed by #362
